# Sensitivity test: Patch1 on BOT, Patch2 on TOP.

[run]
description = "sensitivity test: Patch1 on BOT, Patch2 on TOP"

[antenna.A]
label      = "Patch1"
mount_site = "test"
receiver   = "BOT"

[antenna.B]
label      = "Patch2"
mount_site = "test"
receiver   = "TOP"
